# Configuration for generating synthetic data around a tilted cartpole state
centroid: [0, 0, -0.1, 0]  # [x, x_dot, theta, theta_dot] - slight tilt to the left
eps: 0.05                  # Small region around the centroid
shape: spherical           # Sample from a sphere
dim: 4                     # State dimension for cartpole
label: 0                   # Action 0 (push left)
num_samples: 200           # Number of synthetic samples
